.\" Manpage for sc
.\" Report errors or typos to https://github.com/ErikBoesen/sc/issues
.TH vs 7 "11 Oct 2017" "1.0.0" "sc man page"

.SH NAME
vs \- CLI tool for interaction with Schoology

.SH SYNOPSIS
.B sc
.TP
At this point there are no command line options supported.

.SH DESCRIPTION
sc is a helpful tool for interacting with Schoology via the command line.

.SH BUGS
Please see current issues on
.UR https\://\:github.com/ErikBoesen/sc/issues
issue tracker
.UE ,
and report any bugs or request features you'd like.

.SH AUTHORS
This software is maintained by
.MT me@\:erikboesen.com
Erik Boesen
.ME
since 2017 on
.UR https\://\:github.com/ErikBoesen/sc
GitHub
.UE .
This manual page was written by
.MT me@\:erikboesen.com
Erik Boesen
.ME .
